### ISSUE TITLE
Does it work with free account?

### ISSUE THREAD

**Issue by khoroshyy** [XaviTorello/mail2googlegroup#2]
Hi.
Does it work with a free Gmail account or I need a Gsuite subscription?
Thanks.
Petro.

**Comment by XaviTorello** [comment]
Hi @khoroshyy, I'm not sure but it should work if you can interact with the `Groups migration API`.

I used to migrate email from several sources to a group (linked to a GSuite).

Have you tried it?

Cheers!

**Comment by XaviTorello** [comment]
Any news @khoroshyy? If not I'll close this issue

**Comment by khoroshyy** [comment]
Hi.
I had no time to look better into it. I will reopen if i encounter any
issues later on.
Best.
Petro.
